### ISSUE TITLE
12. Glossary

### ISSUE THREAD

**Issue by UO257247** [Arquisoft/radarin_en2a#12]
Each member of the group will write down new terms for the glossary

**Comment by uo271694** [comment]
Added this terms to the glossary:

- Solid
- POD
- Load test
- Acceptance test
- Unit test
- Domain layer
- Presentation layer

**Comment by UO269911** [comment]
Added:
- MVC
- OOP

**Comment by alonsogago** [comment]
Terms added:

- Usability
- Decentralization

**Comment by UO257247** [comment]
Terms added: 
 
* Domain model
* User experience (UX)
