### ISSUE TITLE
Investigate how to get the location from a device using react native

### ISSUE THREAD

**Issue by alonsogago** [Arquisoft/radarin_en2a#47]
Check the google maps API as well as others that could help`developing this feature

**Comment by UO257247** [comment]
Interesting to have a look at this: https://www.pluralsight.com/guides/how-to-use-geolocation-call-in-reactjs

**Comment by alonsogago** [comment]
There are several different libraries that can be used for the same purpose but all of them work in the same way and seem pretty easy to use.
To ask the user to grant access to his location there are different methods depending on the operating system of the device.
The methods getCurrentPosition() and watchPosition() are common to all packages, libraries and APIs and are the way to obtain the location and perform a callback whenever it changes. We could get the coordinates of the location with this methods and write them to the user's POD.
The Google Maps API is not free, but it gives every user 200$ of free credit and this is supossed to be sufficient for the majority of users and developers. After getting the location with the previous methods, we could enter the coordinates into this API  so a map centered in that position would be generated. Plus, it allows to highlight other locations, so we can load the user's friends locations so they can find themselves in the map.

**Comment by alonsogago** [comment]
Helpful links from research:

- [https://reactnative.dev/docs/geolocation](https://reactnative.dev/docs/geolocation)
- [https://developer.mozilla.org/en-US/docs/Web/API/Geolocation](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation)
- [https://reactnative.directory/?search=geolocation](https://reactnative.directory/?search=geolocation)
- [https://www.digitalocean.com/community/tutorials/react-geolocation-react-native](https://www.digitalocean.com/community/tutorials/react-geolocation-react-native)
- [https://www.npmjs.com/package/react-native-geolocation-service](https://www.npmjs.com/package/react-native-geolocation-service)
- [https://developer.mozilla.org/es/docs/Web/API/Geolocation_API](https://developer.mozilla.org/es/docs/Web/API/Geolocation_API)
- [https://www.w3schools.com/html/html5_geolocation.asp](https://www.w3schools.com/html/html5_geolocation.aspl)
- [https://developers.google.com/maps/documentation/javascript/libraries?hl=es-419](https://developers.google.com/maps/documentation/javascript/libraries?hl=es-419)
- [https://developers.google.com/maps/documentation/javascript/overview?hl=es-419](https://developers.google.com/maps/documentation/javascript/overview?hl=es-419)
- [https://mappinggis.com/2018/02/primeros-pasos-con-la-api-javascript-de-google-maps/](https://mappinggis.com/2018/02/primeros-pasos-con-la-api-javascript-de-google-maps/)

**Comment by UO257247** [comment]
Already obtained a location from an Android device
