### ISSUE TITLE
Implement the webapp views left

### ISSUE THREAD

**Issue by uo271694** [Arquisoft/radarin_en2a#77]

**Comment by uo271694** [comment]
First version of the location menu, without any style applied.
![d21d45bc0b3427eb3f2bffc9eb3af573](https://user-images.githubusercontent.com/71765462/113732415-db961000-96f9-11eb-9a32-d4a56f35ea3e.png)

**Comment by uo271694** [comment]
Continuing with the location editor, only works for current locations. Comment a photo are not saved
![4db2eb21e5d2be3a37cf47e599b355f5](https://user-images.githubusercontent.com/71765462/114002251-fc2aab00-985c-11eb-9bf6-c07e8f961abf.png)

**Comment by UO257247** [comment]
A new drop down menu has been placed

![imagen_2021-04-10_192415](https://user-images.githubusercontent.com/56041034/114278945-5761c680-9a32-11eb-9dd3-2d009cfa370f.png)
![imagen_2021-04-10_192531](https://user-images.githubusercontent.com/56041034/114278967-84ae7480-9a32-11eb-87c0-7ba773f303c8.png)

**Comment by uo271694** [comment]
Delete location now (at least) working
![2021-04-11-11-13-47](https://user-images.githubusercontent.com/71765462/114298968-342e2a00-9ab9-11eb-837c-df9b0372f788.gif)

**Comment by uo271694** [comment]
Removed pictures from locations, added a different marker (green) from previous locations and added a link to the friend in each marker
![2d1d53d19203822b07d32a0fe8009c3c](https://user-images.githubusercontent.com/71765462/114312733-fd293a00-9af3-11eb-81ac-6883bfd281f3.png)
