### ISSUE TITLE
Problems with the npm run docs command on my computer

### ISSUE THREAD

**Issue by alonsogago** [Arquisoft/radarin_en2a#9]
Whenever I execute the npm run docs  command I get the same problem even though i have everything installed and I did all over again all the steps from the laboratory lesson.
@pglez82 
![image](https://user-images.githubusercontent.com/60621183/107550998-02d8d100-6bd2-11eb-8be7-639ae2dc5278.png)

**Comment by pglez82** [comment]
Hi Alonso,

The error message tells you that is not finding asciidoc. If you have installed ruby, you need to install asciidoc with `gem install asciidoctor asciidoctor-diagram`. If that command goes through then `npm run docs` should work. If the `gem install` fails paste the output here to check what is happening.

Pablo
